# *** NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.***

# Import Library

In [0]:
import numpy as np

# Size,Shape

In [0]:
a=np.array([1,2,3,3])
a
print("printing 1 d array", a)
b=np.array([[1,2,3,4],[1,2,3,4]])
print("printing 2 d array",b)
print("getting dimension of matrix 1d/2d/3d",a.ndim)    #dimension is rank
print("getting dimension of matrix 1d/2d/3d",b.ndim)
print("shape of matrix a rxc (a is one d so its show as vector )",a.shape)
print("shape of matrix b rxc ",b.shape)
print("describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted. int32orint16orint64-----",a.dtype)
print("describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.  int32orint16orint64-----",b.dtype)
print("Returns the size in bytes of each element of the matrix b",b.itemsize)
print("return total size of matrix a ",a.size)
print("return total element of matrix b ",b.size)
print("return total size of matrix b ",b.nbytes)


printing 1 d array [1 2 3 3]
printing 2 d array [[1 2 3 4]
 [1 2 3 4]]
getting dimension of matrix 1d/2d/3d 1
getting dimension of matrix 1d/2d/3d 2
shape of matrix a rxc (a is one d so its show as vector ) (4,)
shape of matrix b rxc  (2, 4)
describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted. int32orint16orint64----- int64
describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.  int32orint16orint64----- int64
Returns the size in bytes of each element of the matrix b 8
return total size of matrix a  4
return total element of matrix b  8
return total size of matrix b  64


# Array Creation

In [0]:
y=np.zeros(5)  #NULL vector of size 5
y=np.ones(5)    #unit vector with float values of size 5
#print(y)
y=np.ones((2,2))   
#print(y)
y=np.eye(3)      #identity matrix of 3x3
#print(y)
#print(np.nonzero(y))      #prints all non zero elements of vector
y=np.zeros((2,4))
#print(y)
#print(y.shape)
y=np.full((3,3),2+6j,dtype=complex)  
print("syntax is np.full((r,c),fill_value,dtype=None||cpmplex)",y)
y=np.linspace(0,10,20)
print("evenly spaced values in vector with linspace(initial_value,final_value,total_size)",y)


syntax is np.full((r,c),fill_value,dtype=None||cpmplex) [[2.+6.j 2.+6.j 2.+6.j]
 [2.+6.j 2.+6.j 2.+6.j]
 [2.+6.j 2.+6.j 2.+6.j]]
evenly spaced values in vector with linspace(initial_value,final_value,total_size) [ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [0]:
y=np.arange(0,90,1) 
#print(y)  
y=np.arange(90)      #both same take vlue from 0 to 89
#print(y) 
y=np.arange(9).reshape(3,3)
y=np.random.random((3,4))
z=y.reshape(2,2,3)
print(y)
#print(z)
k=y.flatten(order='C')   #flatten by default and stored as r0 r1 ...
k1=y.flatten(order='F')  #flatten and stored as c0 c1 ...
print("\n",k,"\n \n",k1)

AxisError: ignored


 random generator

In [0]:
y=np.random.random(10)   #10 random value generated betw 0 & 1
y.shape
y=np.random.random((5,5))   #random value bet 0 & 1 5x5 dimension
print(y)


[[0.27853751 0.32622508 0.19439998 0.39769289 0.50565974]
 [0.47580485 0.10666743 0.50946082 0.36205413 0.00436598]
 [0.02499233 0.57962857 0.61495551 0.30582168 0.87544567]
 [0.5087905  0.32924238 0.56831691 0.13643723 0.80498653]
 [0.04336176 0.20818725 0.18920943 0.85471688 0.21923787]]
sorted matrix element by row
None
another sorted matrix element by row
sorted matrix element by col
[[0.19439998 0.27853751 0.32622508 0.39769289 0.50565974]
 [0.00436598 0.10666743 0.36205413 0.47580485 0.50946082]
 [0.02499233 0.30582168 0.57962857 0.61495551 0.87544567]
 [0.13643723 0.32924238 0.5087905  0.56831691 0.80498653]
 [0.04336176 0.18920943 0.20818725 0.21923787 0.85471688]]
mean value of matrix  0.37696795637881664


# ARRAY INDEXING

In [0]:
z=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(z)
y=np.array(z[1:3,1:3])
y=z[:2,-1:2]    #  give empty 
print(y)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[]


In [0]:
print("particular element acess ",b[1,1])
print("get spacific row ",b[0,:])
print("get specific col",b[:,2])
print("get certain rows and col ", b[0:2,1:3])


particular element acess  2
get spacific row  [1 2 3 4]
get specific col [3 3]
get certain rows and col  [[2 3]
 [2 3]]


In [0]:
y=z[:2,:2]     #till 2nd row and 2nd col not row index
#print(y)
y=z[:-2,:-2]       #leave last 2 row and leave last 2 col
#print(y)
y=z[0:-1,0:-1]    #leave last row and leave last col
#print(y)
y=z[:2,::2]
#print("array with first two rows and alternate col",y)
y=z[[0,2,3,1],[1,2,1,2]]
print("array with value at index (0,1),(2,2),(3,1),(1,2)",y)

array with value at index (0,1),(2,2),(3,1),(1,2) [2 3 2 3]


Basic operation and BroadCasting ,Unary Operators Binary 
The Broadcasting Rule: In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one.





In [0]:
y=z+10
#print("z+10 \n",y)   #broadcasting examples
y=z-4
#print("\n z-4 \n",y)
y=z*2
#print("\n z*2 \n",y)
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a[:, np.newaxis] + b)   #broadcasting
#print("transpose is basically y.T",y.T)
#print(y.max(),y.min())  #max & min elemnts of entire matrix
#print("max by row is y.max(axis=1) \n",y.max(axis=1))  #print all rowwise max same for min as well
#print("max by col is y.max(axis=0)\n",y.max(axis=0))    #print all colwise max same for min as well
#print("sum of all element of matrix y.sum()",y.sum())
#print("sum along each row ",y.sum(axis=1))  
#print("sum along each col ",y.sum(axis=0)) 
#print("squaring each element ",y**2) 
#print("summing element wise 2 matrix with condition of same dimension ",z+y)
#print("Multiplication element wise 2 matrix with condition of same dimension ",z*y)
print("Multiplication of 2 matrix with condition (r1,c)x(c,r2) of same dimension ",z.dot(y))
print("element wise sine \n",np.sin(y))
print("\n element wise exponential ",np.exp(y))
print("\n element wise squar root",np.sqrt(z))
y.sort() 
print("another sorted matrix element by row")
np.sort(y,axis=0)
#print(y)


[[5 6 7]
 [6 7 8]
 [7 8 9]]
Multiplication of 2 matrix with condition (r1,c)x(c,r2) of same dimension  [[20 40 60 80]
 [20 40 60 80]
 [20 40 60 80]
 [20 40 60 80]]
element wise sine 
 [[ 0.90929743 -0.7568025  -0.2794155   0.98935825]
 [ 0.90929743 -0.7568025  -0.2794155   0.98935825]
 [ 0.90929743 -0.7568025  -0.2794155   0.98935825]
 [ 0.90929743 -0.7568025  -0.2794155   0.98935825]]

 element wise exponential  [[   7.3890561    54.59815003  403.42879349 2980.95798704]
 [   7.3890561    54.59815003  403.42879349 2980.95798704]
 [   7.3890561    54.59815003  403.42879349 2980.95798704]
 [   7.3890561    54.59815003  403.42879349 2980.95798704]]

 element wise squar root [[1.         1.41421356 1.73205081 2.        ]
 [1.         1.41421356 1.73205081 2.        ]
 [1.         1.41421356 1.73205081 2.        ]
 [1.         1.41421356 1.73205081 2.        ]]
another sorted matrix element by row


array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

# Stacking

In [0]:
a1=np.array([[1,2,3],[4,5,6]])
b1=np.array([[7,8,9],[10,11,12]])
print("vertical stacking \n ",np.vstack((a1,b1)))
print("horizontal stacking \n ",np.hstack((a1,b1)))
print("column inserted  in last \n ",np.column_stack((a1,[0,0]))) #[0,0] as column added to last 
print("concatening to 2nd axis [a1 b1] ",np.concatenate((a1,b1),1))

vertical stacking 
  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
horizontal stacking 
  [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
column inserted  in last 
  [[1 2 3 0]
 [4 5 6 0]]
concatening to 2nd axis [a1 b1]  [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


LinearAlgebra

In [0]:
z1=np.array([[6, 1, 1], 
              [4, -2, 5], 
              [2, 8, 7]])
print("\n rank of matrix ",np.linalg.matrix_rank(a1))
print("\n detreminant of matrix ",np.linalg.det(z1))
print("\n trace of matrix ",np.trace(a1))
print("\n Inverse of matrix ",np.linalg.inv(z1))
print("\n  matrix ised to some power",np.linalg.matrix_power(z1,3))
coef=np.array([[1, 2], [3, 4]])  #coefficient values of equation
const = np.array([8, 18]) #constatnt values of equation
print("Solution of linear equations:", np.linalg.solve(coef, const))


 rank of matrix  2

 detreminant of matrix  -306.0

 trace of matrix  6

 Inverse of matrix  [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

  matrix ised to some power [[336 162 228]
 [406 162 469]
 [698 702 905]]
Solution of linear equations: [2. 3.]
